### ISSUE TITLE
duplicate lemmas

### ISSUE THREAD

**Issue by balmas** [alpheios-project/stg#1]
the steingass ids and defs data files have 69868 entries, but only 68001 of those are unique lemmas. Needs to be investigated to see if this is a problem in the TEI or in the lemma extraction script  -  Off the top of my head they look like legitimate homonyms- but I can check the tei input file if you confirm the link to the one you are using.

**Comment by balmas** [comment]
List of lemmas that appear multiple times
[dups.txt](https://github.com/alpheios-project/stg/files/1555844/dups.txt)

**Comment by balmas** [comment]
@abrasax if you have a chance to look at this it would be really helpful

**Comment by abrasax** [comment]
Off the top of my head they look like legitimate homonyms. If you give me
the link to the full dictionary file from which you actually extracted the
dups I can double check.

**Comment by balmas** [comment]
https://github.com/alpheios-project/stg/blob/master/db/lexica/per/stg/ustg.xml?raw=true

**Comment by abrasax** [comment]
Yes they appear to all be homonyms, so should all be returned with some
sort of separator, perhaps just repetition of the word in bold. I have not
noticed any cases where the part of speech changes, but that is certainly
possible in Arabic, so the full record of each should be returned in the
full display.

**Comment by balmas** [comment]
hmm. ok. I believe the other lexicons deal with this by appending a digit after each homonym to distinguish them. I will adjust the lookup code to handle either scenario. Thanks

**Comment by abrasax** [comment]
Yes, a numeral would be the best way to distinguish them.
